// Bundles beautiful-mermaid's ASCII path (no elkjs, no DOM) into one ESM file
// the hooks module imports by relative path: hooks modules run with no Node
// and cannot resolve bare specifiers.
import { build } from 'esbuild'
import { readFileSync, writeFileSync } from 'node:fs'

const entry = 'scripts/vendor-entry.ts'
writeFileSync(entry, `export { renderMermaidAscii } from '../node_modules/beautiful-mermaid/src/ascii/index.ts'\n`)

// Upstream's A* searches an unbounded quadrant, so an edge whose target is
// fenced in expands cells for ~20s and dies on "Map maximum size exceeded";
// inside a hook that is the module's whole budget. Callers already fall back
// when getPath returns null, so a bounded search degrades to a straight
// segment instead. Remove once upstream bounds it.
const PATHFINDER_ANCHOR = '  while (pq.length > 0) {\n    const current = pq.pop()!.coord\n'
const PATHFINDER_PATCH =
  '  const MAX_EXPANSIONS = 40_000\n' +
  '  let expansions = 0\n' +
  '  while (pq.length > 0) {\n' +
  '    if (++expansions > MAX_EXPANSIONS) return null\n' +
  '    const current = pq.pop()!.coord\n'

const boundedAStar = {
  name: 'bounded-a-star',
  setup(api) {
    api.onLoad({ filter: /beautiful-mermaid\/src\/ascii\/pathfinder\.ts$/ }, args => {
      const source = readFileSync(args.path, 'utf8')
      if (!source.includes(PATHFINDER_ANCHOR)) throw new Error(`${args.path}: A* loop changed upstream; refresh the patch`)
      return { contents: source.replace(PATHFINDER_ANCHOR, PATHFINDER_PATCH), loader: 'ts' }
    })
  },
}

await build({
  entryPoints: [entry],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2023',
  outfile: 'hooks/vendor/mermaid-ascii.js',
  legalComments: 'none',
  plugins: [boundedAStar],
  banner: { js: '// Generated by scripts/build-vendor.mjs from beautiful-mermaid (MIT), A* bounded. Do not edit.' },
})
