// Bundles claude-mermaid's diagram renderer (the sibling package at the
// repository root, its vendored beautiful-mermaid included) into one ESM
// file this plugin imports by relative path: an installed plugin is a copy
// of this folder alone, so nothing outside it can be imported at run time.
import { build } from 'esbuild'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const ROOT = new URL('../../', import.meta.url).pathname
const entry = join(ROOT, 'hooks/diagrams.ts')
const out = new URL('../hooks/vendor/diagrams.js', import.meta.url).pathname

await build({
  entryPoints: [entry],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2023',
  outfile: out,
  legalComments: 'none',
  banner: { js: '// Generated by scripts/build-vendor.mjs from ../hooks/diagrams.ts (claude-mermaid). Do not edit.' },
})

// the declarations, so the hooks module type-checks against the bundle
const tmp = mkdtempSync(join(tmpdir(), 'claude-markdown-dts-'))
execFileSync('bunx', ['-p', 'typescript', 'tsc', '--ignoreConfig', entry, '--declaration', '--emitDeclarationOnly', '--skipLibCheck', '--allowImportingTsExtensions', '--module', 'esnext', '--moduleResolution', 'bundler', '--target', 'es2023', '--outDir', tmp], { cwd: ROOT, stdio: 'inherit' })
const dts = readFileSync(join(tmp, 'diagrams.d.ts'), 'utf8')
writeFileSync(out.replace(/\.js$/, '.d.ts'), '// Generated by scripts/build-vendor.mjs. Do not edit.\n' + dts)
rmSync(tmp, { recursive: true, force: true })
